version: "2"
services:
  chirpstack-simulator:
    build:
      context: .
      dockerfile: Dockerfile-devel
    command: >
      bash -c "make build && ./build/chirpstack-simulator --config simulator.toml"
    volumes:
      - ./:/chirpstack-simulator
    ports:
      - "9002:9002"
      - "9001:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
