package api

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/brocaar/chirpstack-simulator/internal/as"
	"github.com/chirpstack/chirpstack/api/go/v4/api"
	log "github.com/sirupsen/logrus"
)

// Organization represents a tenant returned by the API.
type Organization struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// CreateOrganizationRequest is the HTTP request body for creating a tenant.
type CreateOrganizationRequest struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

// handleListOrganizations returns all tenants from ChirpStack.
func handleListOrganizations(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeJSON(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
		return
	}

	if !as.IsConnected() {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": "ChirpStack API connection not established"})
		return
	}

	// Sync missing organization configs before returning the list
	syncMissingOrgConfigs()

	resp, err := as.Tenant().List(context.Background(), &api.ListTenantsRequest{
		Limit: 100,
	})
	if err != nil {
		log.WithError(err).Error("organizations: list tenants error")
		writeJSON(w, http.StatusBadGateway, map[string]string{
			"error": "Failed to connect to ChirpStack API: " + err.Error(),
		})
		return
	}

	orgs := make([]Organization, 0, len(resp.GetResult()))
	for _, t := range resp.GetResult() {
		orgs = append(orgs, Organization{
			ID:   t.GetId(),
			Name: t.GetName(),
			// TenantListItem does not include Description; keep empty.
		})
	}

	writeJSON(w, http.StatusOK, map[string]interface{}{
		"organizations": orgs,
		"count":         len(orgs),
	})
}

// handleCreateOrganization creates a new tenant in ChirpStack.
func handleCreateOrganization(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeJSON(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
		return
	}

	if !as.IsConnected() {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": "ChirpStack API connection not established"})
		return
	}

	var req CreateOrganizationRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid JSON: " + err.Error()})
		return
	}

	if req.Name == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "organization name is required"})
		return
	}

	// Create tenant via ChirpStack gRPC API.
	// ID is auto-generated by ChirpStack (UUID).
	tenant := &api.Tenant{
		Name:            req.Name,
		Description:     req.Description,
		CanHaveGateways: true,
	}

	resp, err := as.Tenant().Create(context.Background(), &api.CreateTenantRequest{
		Tenant: tenant,
	})
	if err != nil {
		log.WithError(err).WithField("name", req.Name).Error("organizations: create tenant error")
		writeJSON(w, http.StatusBadGateway, map[string]string{
			"error": "Failed to connect to ChirpStack API: " + err.Error(),
		})
		return
	}

	log.WithFields(log.Fields{
		"id":   resp.GetId(),
		"name": req.Name,
	}).Info("organizations: tenant created")

	writeJSON(w, http.StatusCreated, Organization{
		ID:          resp.GetId(),
		Name:        req.Name,
		Description: req.Description,
	})
}

// handleDeleteOrganization deletes a tenant from ChirpStack.
func handleDeleteOrganization(w http.ResponseWriter, r *http.Request, id string) {
	if r.Method != http.MethodDelete {
		writeJSON(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
		return
	}

	if !as.IsConnected() {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": "ChirpStack API connection not established"})
		return
	}

	_, err := as.Tenant().Delete(context.Background(), &api.DeleteTenantRequest{
		Id: id,
	})
	if err != nil {
		log.WithError(err).WithField("id", id).Error("organizations: delete tenant error")
		writeJSON(w, http.StatusBadGateway, map[string]string{
			"error": "Failed to connect to ChirpStack API: " + err.Error(),
		})
		return
	}

	log.WithField("id", id).Info("organizations: tenant deleted")
	writeJSON(w, http.StatusOK, map[string]string{"status": "deleted", "id": id})
}
