export const state = {
    language: localStorage.getItem("sim_language") || "tr",
    organizations: [],
    filteredOrgs: [],
    activeOrgId: null,
    activeDpId: null,
    tableSort: { key: "name", dir: "asc" },
    tablePage: 1,
    tablePageSize: 5,
    searchQuery: "",
    currentTab: "overview",
    drawerOpen: false,
    drawerMode: "edit",
    currentStatus: "idle",
    dpList: [],
    dpFiltered: [],
    dpSort: { key: "name", dir: "asc" },
    dpPage: 1,
    dpPageSize: 5,
    dpSearchQuery: "",
    dpTenantFilter: "",
    netList: [],
    netFiltered: [],
    netSort: { key: "name", dir: "asc" },
    netPage: 1,
    netPageSize: 5,
    netSearchQuery: "",
    netTenantFilter: "",
    devList: [],
    devFiltered: [],
    devSort: { key: "name", dir: "asc" },
    devPage: 1,
    devPageSize: 5,
    devSearchQuery: "",
    devTenantFilter: "",
    devStatusList: [],
    devStatusFiltered: [],
    devStatusSort: { key: "device_name", dir: "asc" },
    devStatusPage: 1,
    devStatusPageSize: 5,
    devStatusSearchQuery: "",
    applications: [],
    appFiltered: [],
    appSearchQuery: "",
    appSort: { key: "name", dir: "asc" },
    appPage: 1,
    appPageSize: 5,
    deviceIntervals: {},
    devIntPage: 1,
    devIntPageSize: 10,
    devIntSearchQuery: "",
    devIntSort: { key: "name", dir: "asc" },
    devIntFiltered: [],

    // Map, Charts and Simulation state
    pollTimer: null,
    map: null,
    mapMarkers: [],
    mapLines: [],
    metricsChart: null,
    chartDataHistory: {
        labels: [],
        uplinks: [],
        joinRequests: [],
        joinAccepts: []
    },
    maxHistoryPoints: 20,
    prevMetrics: null
};
