import { state } from "./state.js";

export const translations = {
    tr: {
        app_title: "ChirpStack Simülatörü",
        nav_grp_mgmt: "İzleme",
        nav_organizations: "Organizasyonlar",
        nav_live_map: "Canlı İzleme",
        title_live_map: "Canlı İzleme",
        subtitle_live_map: "Cihazların canlı konumlarını ve ağ paket aktivitelerini takip edin.",
        drawer_subtitle_edit: "Simülasyon ayarlarını yapılandırın",
        drawer_subtitle_view: "Simülasyon ayarlarını görüntüleyin",
        dp_drawer_title: "Cihaz Profili Düzenle",
        dp_drawer_subtitle: "Cihaz profilinin yapılandırma bilgilerini güncelleyin",
        dev_drawer_title: "Cihaz Düzenle",
        dev_drawer_subtitle: "Cihazın yapılandırma bilgilerini güncelleyin",
        modal_add_dev_disabled_check: "Cihazı devre dışı bırak",
        metrics_uplinks: "Gönderilen Uplink",
        metrics_join_reqs: "Join İsteği",
        metrics_joins: "Başarılı Join",
        metrics_gw_uplinks: "GW Uplink",
        metrics_gw_downlinks: "GW Downlink",
        console_src_all: "Tüm Günlükler",
        console_src_local: "Sadece Yerel Simülatör",
        console_src_remote: "Sadece Uzak Bağlantı (ChirpStack)",
        nav_grp_apps: "Yönetim",
        nav_networks: "Ağlar",
        nav_device_profiles: "Cihaz Profilleri",
        nav_devices: "Cihazlar",
        nav_device_status: "Cihaz Durumları",
        nav_system_logs: "Sistem Logları",
        nav_log_center: "Log Merkezi",
        placeholder_search_log: "Log ara...",
        log_level_all: "Tüm Seviyeler",
        log_level_success: "Başarılı",
        log_level_info: "Bilgi",
        log_level_warn: "Uyarı",
        log_level_error: "Hata",
        btn_export_logs: "Dışa Aktar",
        btn_clear_logs: "Temizle",
        system_logs_subtitle: "Sistem olaylarını ve simülasyon veri akışını izleyin.",
        tab_system_events: "Sistem Olayları",
        tab_live_console: "Canlı Konsol",
        no_logs_found: "Log kaydı bulunamadı.",
        no_logs_to_export: "Dışa aktarılacak log bulunamadı.",
        confirm_clear_logs: "Tüm sistem loglarını silmek istediğinize emin misiniz?",
        nav_grp_system: "Sistem",
        nav_settings: "Ayarlar",
        nav_console: "Konsol",
        nav_info: "Bilgi Notları",
        top_bootstrap: "Yeni Proje Oluştur",
        top_bootstrap_title: "Hızlı Kurulum Sihirbazı",
        wiz_scenario_preset: "Simülasyon Şablonu (Scenario Preset)",
        wiz_preset_default: "Standart Simülasyon (Rastgele Konum & Sabit Payload)",
        wiz_preset_batman_oil: "Batman Raman Petrol Sahası (Kuyu Telemetrisi)",
        wiz_preset_hint: "Kurulum sonrasında cihazların konumu ve veri üretim betikleri şablona göre otomatik ayarlanır.",
        top_start: "▶ Başlat",
        top_start_title: "Simülasyonu Başlat",
        top_stop: "■ Durdur",
        top_stop_title: "Simülasyonu Durdur",
        badge_no_conn: "Bağlantı Yok",
        badge_connected: "Bağlantı Var",
        badge_idle: "IDLE",
        badge_running: "RUNNING",
        badge_starting: "STARTING",
        badge_stopping: "STOPPING",
        theme_toggle_title: "Tema Değiştir",
        lang_toggle_title: "Dili Değiştir (Switch Language)",
        console_title: "Canlı Log Konsolu",
        console_subtitle: "Simülasyon cihazlarına ait veri akışını gerçek zamanlı izleyin.",
        console_filter_placeholder: "🔍 Cihaz veya log ara (örn: sim-dev-1)...",
        console_clear: "🧹 Ekranı Temizle",
        console_placeholder: "Simülasyon başlatıldığında canlı loglar burada görünecektir.",
        info_title: "Simülasyon Çalıştırma Kılavuzu",
        info_subtitle: "Simülatörün adım adım kullanım yönergeleri.",
        info_step_1: "<strong>Ağ Yapılandırması:</strong> Sağ çekmeceyi açarak simülasyon ayarlarını düzenleyin ve <em>\"Ayarları Kaydet\"</em> ile kaydedin. Yeni bir ağ kurmak için üst barda bulunan <em>\"Yeni Oluştur\"</em> sihirbazını kullanabilirsiniz.",
        info_step_2: "<strong>Simülasyonu Başlatma:</strong> Üst menüdeki yeşil <strong>\"▶ Başlat\"</strong> butonuna tıklayın. Veritabanındaki tüm organizasyonlar aynı anda paralel çalışmaya başlayacaktır.",
        info_step_3: "<strong>Ağ Katılımı (OTAA):</strong> Cihazlar otomatik olarak ChirpStack üzerinde OTAA katılım isteği gönderir ve onaylandığında veri göndermeye başlar.",
        info_step_4: "<strong>Canlı İzleme ve Filtreleme:</strong> <strong>\"Konsol\"</strong> sekmesinden veri akışını izleyin. Yoğun log akışında arama kutusunu kullanarak spesifik bir cihazı (örn: <code>sim-dev-1</code>) filtreleyin.",
        info_step_5: "<strong>Süre Güncelleme:</strong> Çalışma sırasında <strong>\"Cihazlar\"</strong> listesinden veri sıklığı ayarını (örn: 4 dk) değiştirin. Sistem simülatörü otomatik olarak durdurup yeni ayarla kesintisiz yeniden başlatacaktır.",
        info_step_6: "<strong>Simülasyonu Durdurma:</strong> İstediğiniz zaman üst menüdeki kırmızı <strong>\"🛑 Durdur\"</strong> butonuna basarak tüm cihazları pasif konuma çekebilirsiniz.",
        
        // New Localization Keys
        title_overview: "Organizasyonlar",
        subtitle_overview: "Sistemdeki ana organizasyonları ve üst çatı yapıları yönetin.",
        btn_add_org: "+ Yeni Organizasyon Ekle",
        placeholder_search_org: "Organizasyon ara...",
        table_org_name: "Organizasyon Adı",
        table_org_status: "Durum",
        table_org_id: "ID",
        table_org_net_count: "Ağ Sayısı",
        table_org_dp_count: "Profil Sayısı",
        table_org_dev_count: "Cihaz Sayısı",
        table_org_date: "Kayıt Tarihi",
        table_actions: "İşlemler",
        empty_state_org_title: "Henüz organizasyon yok",
        empty_state_org_text: "Üst bardaki \"Yeni Oluştur\" butonuyla hızlı kurulum yapabilirsiniz.",
        footer_page_size: "Sayfa Başına:",
        footer_total_org: "Toplam: <strong>{count}</strong> Organizasyon",

        title_networks: "Ağlar",
        subtitle_networks: "ChirpStack tenant'larına ait LoRaWAN ağlarını yönetin.",
        btn_add_net: "+ Yeni Ağ",
        select_all_tenants: "Tüm Tenant'lar",
        placeholder_search_net: "Ağ ara...",
        table_net_name: "Ağ Adı",
        table_net_org: "Organizasyon",
        table_net_created_at: "Oluşturma Tarihi",
        empty_state_net_title: "Henüz ağ yok",
        empty_state_net_text: "Üst bardaki \"Yeni Oluştur\" butonuyla hızlı kurulum yapabilirsiniz.",
        footer_total_net: "Toplam: <strong>{count}</strong> Ağ",

        title_dp: "Cihaz Profilleri",
        subtitle_dp: "ChirpStack tenant'larına ait LoRaWAN cihaz profillerini yönetin.",
        btn_add_dp: "+ Yeni Cihaz Profili",
        placeholder_search_dp: "Cihaz profili ara...",
        table_dp_name: "Profil Adı",
        table_dp_org: "Organizasyon",
        table_dp_region: "Bölge",
        table_dp_mac: "MAC Versiyon",
        table_dp_otaa: "OTAA",
        empty_state_dp_title: "Henüz cihaz profili yok",
        empty_state_dp_text: "Üst bardaki \"Yeni Oluştur\" butonuyla hızlı kurulum yapabilirsiniz.",
        footer_total_dp: "Toplam: <strong>{count}</strong> Profil",

        title_dev: "Cihazlar",
        subtitle_dev: "ChirpStack ağlarına ait LoRaWAN cihazlarını yönetin.",
        btn_add_dev: "+ Yeni Cihaz",
        placeholder_search_dev: "Cihaz ara...",
        table_dev_name: "Cihaz Adı",
        table_dev_org: "Organizasyon",
        table_dev_deveui: "DevEUI",
        table_dev_profile: "Cihaz Profili",
        table_dev_interval: "Sıklık",
        empty_state_dev_title: "Henüz cihaz yok",
        empty_state_dev_text: "Üst bardaki \"Yeni Oluştur\" butonuyla hızlı kurulum yapabilirsiniz.",
        footer_total_dev: "Toplam: <strong>{count}</strong> Cihaz",

        title_dev_status: "Cihaz Durumları",
        subtitle_dev_status: "Simülasyonu aktif olan cihazların anlık bağlantı ve join durumlarını izleyin.",
        table_dev_app: "Ağ",
        table_dev_status: "Durum",
        table_dev_uplink_cnt: "Paket Sayısı",
        empty_state_dev_status_title: "Aktif simüle cihaz yok",
        empty_state_dev_status_text: "Şu anda çalışan aktif simülasyon bulunmuyor. Bir organizasyon seçip simülasyonu başlattığınızda cihaz durumları burada listelenecektir.",
        system_logs_subtitle: "Sistem olaylarını ve simülatör sunucusu günlüklerini takip edin.",

        title_settings: "Ayarlar",
        subtitle_settings: "Sistem, bağlantı ve konsol ayarlarını yönetin.",
        settings_grp_account: "Hesap & Sistem",
        settings_tab_general: "Genel Ayarlar",
        settings_tab_connections: "Bağlantı Ayarları",
        settings_tab_theme: "Konsol Teması",
        settings_tab_logs: "Sistem Logları",
        settings_tab_guide: "Simülasyon Rehberi",
        settings_tab_scripts: "Örnek Betikler (JS)",
        scripts_title: "Doğrudan Kullanılabilir Test Betikleri",
        scripts_subtitle: "ChirpStack simülatörü dinamik JS motoru ile uyumlu, veri dönüşümlerini açıklayan pratik örnekler.",
        scripts_temp_title: "1. Sıcaklık Dalgalanması (Byte Array)",
        scripts_temp_desc: "Cihazın ısınmasını ve soğumasını sinüs dalgası ve gürültü ekleyerek gerçekçi simüle eder. Sıcaklık 10 ile çarpılarak LSB/MSB formatında 2 byte olarak döndürülür.",
        scripts_gps_title: "2. GPS Rota Simülasyonu (Hex String)",
        scripts_gps_desc: "Başlangıç noktasından (örn. İstanbul) itibaren deterministik olarak kuzeydoğu yönünde ilerleyen bir rotayı simüle eder. Koordinatları 100.000 ile çarparak 4'er byte işaretli tamsayıya çevirir ve Hex dizesi olarak döndürür.",
        scripts_meter_title: "3. Akıllı Sayaç & Pil Seviyesi (Byte Array)",
        scripts_meter_desc: "Zamanla artan enerji tüketim endeksini (32-bit) ve her adımda yavaşça azalan pil seviyesini (%100'den geriye) byte dizisi olarak döndürür.",
        scripts_multi_title: "4. Çoklu Sensör Telemetrisi (Hex String)",
        scripts_multi_desc: "Sıcaklık (1 byte), bağıl nem (1 byte) ve fan çalışma durumunu (1 byte, boolean) birleştirip 3 byte Hex formatında döndürür.",
        btn_copy: "Kopyala",
        settings_title_general: "Genel Simülasyon Ayarları",
        settings_sec_rf: "RF Parametreleri",
        settings_lbl_freq: "Frekans (Hz)",
        settings_lbl_bw: "Bant Genişliği (Hz)",
        settings_lbl_sf: "Spreading Factor",
        settings_sec_telemetry: "Telemetri Ayarları",
        settings_lbl_uplink_int: "Uplink Aralığı",
        settings_lbl_fport: "FPort",
        settings_lbl_payload: "Payload (hex)",
        settings_sec_degradation: "Dinamik Simülasyon & Şebeke Bozulmaları",
        settings_lbl_simulate_packet_loss: "Paket Kaybı Simülasyonunu Etkinleştir",
        settings_lbl_packet_loss: "Paket Kaybı (Packet Loss %)",
        settings_lbl_latency_ms: "Gecikme (Latency ms)",
        settings_sec_timing: "Zamanlama Parametreleri",
        settings_lbl_duration: "Süre (0=süresiz)",
        settings_lbl_act_time: "Aktivasyon Süresi",
        settings_sec_mqtt: "MQTT Topic Şablonları",
        settings_lbl_evt_topic: "Event Topic Şablonu",
        settings_lbl_cmd_topic: "Command Topic Şablonu",
        settings_title_connections: "ChirpStack & Broker Bağlantı Ayarları",
        settings_sec_cs_api: "ChirpStack API",
        settings_lbl_api_host: "ChirpStack API Sunucusu (Host:Port)",
        settings_lbl_api_key: "API Anahtarı (JWT Token)",
        settings_lbl_api_insecure: "Güvensiz Bağlantı (Insecure/TLS'siz)",
        settings_sec_mqtt_brokers: "MQTT Broker Bağlantıları",
        settings_lbl_conn_save: "Kaydet ve Bağlan",
        settings_title_theme: "Konsol Tema Ayarları",
        settings_lbl_theme_presets: "Hazır Temalar (Presets)",
        settings_lbl_preview_mode: "Önizleme Modu",
        settings_mode_dark: "Koyu Mod",
        settings_mode_light: "Açık Mod",
        settings_lbl_color_palette: "Renk Paleti (Swatches)",
        settings_lbl_preview: "Önizleme (Live Preview)",
        settings_btn_theme_reset: "Varsayılana Sıfırla",
        settings_btn_theme_save: "✓ Temayı Kaydet ve Uygula",
        settings_title_logs: "Sistem Logları",
        settings_lang_section: "Uygulama Dili",
        settings_lang_label: "Varsayılan Dil (Language)",

        modal_add_org_title: "Yeni Organizasyon Ekle",
        modal_add_org_name: "Organizasyon Adı *",
        modal_add_org_name_placeholder: "Örn: Test Organizasyonu",
        modal_add_org_name_placeholder_wiz: "Örn: Kullanici-X",
        modal_add_org_ref: "Referans ID (opsiyonel)",
        modal_add_org_ref_placeholder: "Boş bırakılırsa ChirpStack otomatik oluşturur",
        modal_add_org_ref_hint: "Sadece referans amaçlıdır. ChirpStack kendi ID'sini üretir.",
        modal_add_org_desc: "Açıklama (isteğe bağlı)",
        modal_add_org_desc_placeholder: "Örn: Test amaçlı organizasyon",
        btn_cancel: "İptal",
        btn_save: "Kaydet",
        btn_save_changes: "Değişiklikleri Kaydet",
        btn_prev: "Geri",
        btn_next: "İleri",

        modal_add_dp_title: "Yeni Cihaz Profili",
        modal_add_dp_tenant: "Tenant *",
        modal_add_dp_desc: "Açıklama (opsiyonel)",
        modal_add_dp_desc_placeholder: "Profil açıklaması",
        modal_add_dp_reg_params: "Bölgesel Parametreler *",
        modal_add_dp_adr: "ADR Algoritması",
        modal_add_dp_otaa_check: "OTAA (Over-The-Air Activation) destekler",
        modal_add_dp_class_b_check: "Class B destekler",
        modal_add_dp_class_c_check: "Class C destekler",
        modal_add_dp_name_placeholder: "Örn: EU868 OTAA Profili",

        modal_add_net_title: "Yeni Ağ Ekle",
        modal_add_net_tenant: "Tenant (Organizasyon) *",
        modal_add_net_desc: "Açıklama (opsiyonel)",
        modal_add_net_desc_placeholder: "Ağ açıklaması",
        modal_add_net_name_placeholder: "Örn: Sensör Ağı",

        modal_add_dev_title: "Yeni Cihaz Ekle",
        modal_add_dev_eui_label: "DevEUI * (16 hex karakter)",
        modal_add_dev_app: "Ağ *",
        modal_add_dev_select_app_first: "Önce ağ seçin",
        select_org_first: "Önce organizasyon seçin",
        select_app_first: "Önce ağ seçin",
        modal_add_dev_desc: "Açıklama (opsiyonel)",
        modal_add_dev_desc_placeholder: "Cihaz açıklaması",
        modal_add_dev_name_placeholder: "Örn: Sensor-001",

        dev_wiz_step_1: "1. Organizasyon & Ağ",
        dev_wiz_step_2: "2. Cihaz Detayları",
        dev_wiz_step_3: "3. Özet & Onay",
        dev_wiz_summary_title: "Oluşturulacak Cihaz Özeti",
        dev_wiz_summary_subtitle: "Lütfen aşağıdaki bilgileri onaylayın.",
        dev_wiz_summary_confirm: "Bu cihazı oluşturmayı onaylıyor musunuz?",

        wiz_step_1: "1. Organizasyon",
        wiz_step_2: "2. Ağ",
        wiz_step_3: "3. Cihaz Profili",
        wiz_step_4: "4. Cihaz",
        wiz_step_5: "5. Özet",
        wiz_org_hint: "Oluşturulacak yeni tenant/organizasyon adı.",
        wiz_app_prefix: "Ağ Öneki *",
        wiz_app_count: "Oluşturulacak Ağ Sayısı *",
        wiz_app_count_hint: "Örn: Kullanici-X-ag-1, Kullanici-X-ag-2...",
        wiz_dp_prefix: "Cihaz Profili Ön Eki *",
        wiz_dp_count: "Oluşturulacak Profil Sayısı *",
        wiz_dp_count_hint: "Örn: Kullanici-X-profile-1, Kullanici-X-profile-2...",
        wiz_dev_prefix: "Cihaz Prefix *",
        wiz_dev_count: "Her Ağdaki Cihaz Sayısı *",
        wiz_dev_count_hint: "Her bir ağda oluşturulacak cihaz adedi.",
        wiz_summary_title: "Oluşturulacak Yapılandırma Özeti",
        wiz_summary_subtitle: "Lütfen oluşturulacak cihazlar için veri sıklığı (Interval) ve profil (Profile) atamalarını özelleştirip onaylayın.",
        wiz_summary_org_lbl: "Org:",
        wiz_summary_net_lbl: "Ağ:",
        wiz_summary_dp_lbl: "Profil:",
        wiz_summary_unit: "adet",
        wiz_table_dev_template: "Cihaz Şablonu",
        wiz_summary_confirm_text: "Bu kurulumu onaylıyor musunuz?",
        wiz_success_title: "Kurulum Başarıyla Tamamlandı",
        wiz_success_subtitle: "ChirpStack üzerinden oluşturma teyit raporu",
        wiz_success_org_lbl: "Organizasyon:",
        wiz_success_total_dev_lbl: "Toplam Cihaz:",
        wiz_success_dev_created_unit: "adet cihaz oluşturuldu.",
        wiz_success_net_created_lbl: "Oluşturulan Ağlar:",
        net_wiz_step_1: "1. Organizasyon",
        net_wiz_step_2: "2. Ağ Detayları",
        net_wiz_step_3: "3. Özet & Onay",
        wiz_success_dp_created_lbl: "Oluşturulan Cihaz Profilleri:",
        wiz_btn_confirm: "Onayla ve Oluştur",
        wiz_btn_close: "Kapat",
        wiz_btn_creating: "Oluşturuluyor...",
        btn_close: "Kapat",
        prev_page: "Geri",
        next_page: "İleri"
    },
    en: {
        app_title: "ChirpStack Simulator",
        nav_grp_mgmt: "Monitoring",
        nav_organizations: "Organizations",
        nav_live_map: "Live Monitoring",
        title_live_map: "Live Monitoring",
        subtitle_live_map: "Track live device locations and network packet activity.",
        drawer_subtitle_edit: "Configure simulation settings",
        drawer_subtitle_view: "View simulation settings",
        dp_drawer_title: "Edit Device Profile",
        dp_drawer_subtitle: "Update configuration info of the device profile",
        dev_drawer_title: "Edit Device",
        dev_drawer_subtitle: "Update configuration info of the device",
        modal_add_dev_disabled_check: "Disable device",
        metrics_uplinks: "Sent Uplink",
        metrics_join_reqs: "Join Request",
        metrics_joins: "Successful Join",
        metrics_gw_uplinks: "GW Uplink",
        metrics_gw_downlinks: "GW Downlink",
        console_src_all: "All Logs",
        console_src_local: "Local Simulator Only",
        console_src_remote: "Remote Connection Only (ChirpStack)",
        nav_grp_apps: "Management",
        nav_networks: "Networks",
        nav_device_profiles: "Device Profiles",
        nav_devices: "Devices",
        nav_device_status: "Device Status",
        nav_system_logs: "System Logs",
        nav_log_center: "Log Center",
        placeholder_search_log: "Search logs...",
        log_level_all: "All Levels",
        log_level_success: "Success",
        log_level_info: "Info",
        log_level_warn: "Warning",
        log_level_error: "Error",
        btn_export_logs: "Export",
        btn_clear_logs: "Clear",
        system_logs_subtitle: "Monitor system events and simulation data stream.",
        tab_system_events: "System Events",
        tab_live_console: "Live Console",
        no_logs_found: "No log entries found.",
        no_logs_to_export: "No logs found to export.",
        confirm_clear_logs: "Are you sure you want to clear all system logs?",
        nav_grp_system: "System",
        nav_settings: "Settings",
        nav_console: "Console",
        nav_info: "Info Notes",
        top_bootstrap: "Create New Project",
        top_bootstrap_title: "Quick Setup Wizard",
        wiz_scenario_preset: "Simulation Scenario Preset",
        wiz_preset_default: "Standard Simulation (Random Location & Static Payload)",
        wiz_preset_batman_oil: "Batman Raman Oil Field (Well Telemetry)",
        wiz_preset_hint: "Device locations and data generation scripts will be configured automatically based on the template.",
        top_start: "▶ Start",
        top_start_title: "Start Simulation",
        top_stop: "■ Stop",
        top_stop_title: "Stop Simulation",
        badge_no_conn: "No Connection",
        badge_connected: "Connected",
        badge_idle: "IDLE",
        badge_running: "RUNNING",
        badge_starting: "STARTING",
        badge_stopping: "STOPPING",
        theme_toggle_title: "Change Theme",
        lang_toggle_title: "Switch Language (Dili Değiştir)",
        console_title: "Live Log Console",
        console_subtitle: "Monitor real-time data streams from simulated devices.",
        console_filter_placeholder: "🔍 Search devices or logs (e.g. sim-dev-1)...",
        console_clear: "🧹 Clear Screen",
        console_placeholder: "Live logs will appear here when simulation starts.",
        info_title: "Simulation Operation Guide",
        info_subtitle: "Step-by-step simulator usage guidelines.",
        info_step_1: "<strong>Network Configuration:</strong> Open the right drawer to edit simulation settings and save with <em>\"Save Settings\"</em>. You can use the <em>\"Create New\"</em> wizard in the top bar to set up a network from scratch.",
        info_step_2: "<strong>Start Simulation:</strong> Click the green <strong>\"▶ Start\"</strong> button in the top menu. All organizations in the database will start running concurrently in parallel.",
        info_step_3: "<strong>Network Join (OTAA):</strong> Devices automatically send an OTAA join request to ChirpStack and begin sending data once activated.",
        info_step_4: "<strong>Live Monitoring & Filtering:</strong> Watch the data stream in the <strong>\"Console\"</strong> tab. In busy streams, use the search box to filter for a specific device (e.g. <code>sim-dev-1</code>).",
        info_step_5: "<strong>Interval Update:</strong> Change the sending frequency of any device in the <strong>\"Devices\"</strong> table while running (e.g., 4 min). The system will automatically stop the simulator, save, and restart it seamlessly.",
        info_step_6: "<strong>Stop Simulation:</strong> Click the red <strong>\"🛑 Stop\"</strong> button in the top menu at any time to set all devices to passive mode.",
        
        // New Localization Keys
        title_overview: "Organizations",
        subtitle_overview: "Manage main organizations and tenants in the system.",
        btn_add_org: "+ Add New Organization",
        placeholder_search_org: "Search organizations...",
        table_org_name: "Organization Name",
        table_org_status: "Status",
        table_org_id: "ID",
        table_org_net_count: "Networks Count",
        table_org_dp_count: "Profiles Count",
        table_org_dev_count: "Devices Count",
        table_org_date: "Registration Date",
        table_actions: "Actions",
        empty_state_org_title: "No organizations yet",
        empty_state_org_text: "You can perform a quick setup using the \"Create New\" button in the top bar.",
        footer_page_size: "Per Page:",
        footer_total_org: "Total: <strong>{count}</strong> Organizations",

        title_networks: "Networks",
        subtitle_networks: "Manage LoRaWAN networks belonging to ChirpStack tenants.",
        btn_add_net: "+ New Network",
        select_all_tenants: "All Tenants",
        placeholder_search_net: "Search networks...",
        table_net_name: "Network Name",
        table_net_org: "Organization",
        table_net_created_at: "Creation Date",
        empty_state_net_title: "No networks yet",
        empty_state_net_text: "You can perform a quick setup using the \"Create New\" button in the top bar.",
        footer_total_net: "Total: <strong>{count}</strong> Networks",

        title_dp: "Device Profiles",
        subtitle_dp: "Manage LoRaWAN device profiles belonging to ChirpStack tenants.",
        btn_add_dp: "+ New Device Profile",
        placeholder_search_dp: "Search device profiles...",
        table_dp_name: "Profile Name",
        table_dp_org: "Organization",
        table_dp_region: "Region",
        table_dp_mac: "MAC Version",
        table_dp_otaa: "OTAA",
        empty_state_dp_title: "No device profiles yet",
        empty_state_dp_text: "You can perform a quick setup using the \"Create New\" button in the top bar.",
        footer_total_dp: "Total: <strong>{count}</strong> Profiles",

        title_dev: "Devices",
        subtitle_dev: "Manage LoRaWAN devices belonging to ChirpStack networks.",
        btn_add_dev: "+ New Device",
        placeholder_search_dev: "Search devices...",
        table_dev_name: "Device Name",
        table_dev_org: "Organization",
        table_dev_deveui: "DevEUI",
        table_dev_profile: "Device Profile",
        table_dev_interval: "Interval",
        empty_state_dev_title: "No devices yet",
        empty_state_dev_text: "You can perform a quick setup using the \"Create New\" button in the top bar.",
        footer_total_dev: "Total: <strong>{count}</strong> Devices",

        title_dev_status: "Device Statuses",
        subtitle_dev_status: "Monitor real-time connection and join status of active simulation devices.",
        table_dev_app: "Network",
        table_dev_status: "Status",
        table_dev_uplink_cnt: "Packet Count",
        empty_state_dev_status_title: "No active simulated devices",
        empty_state_dev_status_text: "There are currently no active simulations running. When you select an organization and start the simulation, device statuses will be listed here.",
        system_logs_subtitle: "Track system events and simulator server logs.",

        title_settings: "Settings",
        subtitle_settings: "Manage system, connection, and console settings.",
        settings_grp_account: "Account & System",
        settings_tab_general: "General Settings",
        settings_tab_connections: "Connection Settings",
        settings_tab_theme: "Console Theme",
        settings_tab_logs: "System Logs",
        settings_tab_guide: "Simulation Guide",
        settings_tab_scripts: "Example Scripts (JS)",
        scripts_title: "Ready-to-Use Test Scripts",
        scripts_subtitle: "Practical examples compatible with the ChirpStack simulator dynamic JS engine, with byte conversions explained.",
        scripts_temp_title: "1. Temperature Fluctuation (Byte Array)",
        scripts_temp_desc: "Simulates heating/cooling using a sine wave plus random noise. The temperature is scaled by 10 and returned as 2 LSB/MSB bytes.",
        scripts_gps_title: "2. GPS Route Simulation (Hex String)",
        scripts_gps_desc: "Simulates a GPS tracker moving northeast from a starting point (e.g., Istanbul). Multiplies coordinates by 100,000 into 32-bit signed integers and returns a Hex string.",
        scripts_meter_title: "3. Smart Meter & Battery (Byte Array)",
        scripts_meter_desc: "Returns an accumulating energy consumption index (32-bit) and a slowly decreasing battery percentage (100% down) as a byte array.",
        scripts_multi_title: "4. Multi-Sensor Telemetry (Hex String)",
        scripts_multi_desc: "Combines temperature (1 byte), relative humidity (1 byte), and a fan status flag (1 byte) into a 3-byte Hex string.",
        btn_copy: "Copy",
        settings_title_general: "General Simulation Settings",
        settings_sec_rf: "RF Parameters",
        settings_lbl_freq: "Frequency (Hz)",
        settings_lbl_bw: "Bandwidth (Hz)",
        settings_lbl_sf: "Spreading Factor",
        settings_sec_telemetry: "Telemetry Settings",
        settings_lbl_uplink_int: "Uplink Interval",
        settings_lbl_fport: "FPort",
        settings_lbl_payload: "Payload (hex)",
        settings_sec_degradation: "Dynamic Simulation & Network Degradation",
        settings_lbl_simulate_packet_loss: "Enable Packet Loss Simulation",
        settings_lbl_packet_loss: "Packet Loss (%)",
        settings_lbl_latency_ms: "Latency (ms)",
        settings_sec_timing: "Timing Parameters",
        settings_lbl_duration: "Duration (0=infinite)",
        settings_lbl_act_time: "Activation Time",
        settings_sec_mqtt: "MQTT Topic Templates",
        settings_lbl_evt_topic: "Event Topic Template",
        settings_lbl_cmd_topic: "Command Topic Template",
        settings_title_connections: "ChirpStack & Broker Connection Settings",
        settings_sec_cs_api: "ChirpStack API",
        settings_lbl_api_host: "ChirpStack API Server (Host:Port)",
        settings_lbl_api_key: "API Key (JWT Token)",
        settings_lbl_api_insecure: "Insecure Connection (Without TLS)",
        settings_sec_mqtt_brokers: "MQTT Broker Connections",
        settings_lbl_conn_save: "Save and Connect",
        settings_title_theme: "Console Theme Settings",
        settings_lbl_theme_presets: "Presets",
        settings_lbl_preview_mode: "Preview Mode",
        settings_mode_dark: "Dark Mode",
        settings_mode_light: "Light Mode",
        settings_lbl_color_palette: "Color Palette (Swatches)",
        settings_lbl_preview: "Live Preview",
        settings_btn_theme_reset: "Reset to Default",
        settings_btn_theme_save: "✓ Save & Apply Theme",
        settings_title_logs: "System Logs",
        settings_lang_section: "Application Language",
        settings_lang_label: "Language",

        modal_add_org_title: "Add New Organization",
        modal_add_org_name: "Organization Name *",
        modal_add_org_name_placeholder: "e.g. Test Organization",
        modal_add_org_name_placeholder_wiz: "e.g. User-X",
        modal_add_org_ref: "Reference ID (optional)",
        modal_add_org_ref_placeholder: "Leave empty for auto-generation",
        modal_add_org_ref_hint: "For reference only. ChirpStack generates its own ID.",
        modal_add_org_desc: "Description (optional)",
        modal_add_org_desc_placeholder: "e.g. Organization for testing",
        btn_cancel: "Cancel",
        btn_save: "Save",
        btn_save_changes: "Save Changes",
        btn_prev: "Back",
        btn_next: "Next",

        modal_add_dp_title: "New Device Profile",
        modal_add_dp_tenant: "Tenant *",
        modal_add_dp_desc: "Description (optional)",
        modal_add_dp_desc_placeholder: "Profile description",
        modal_add_dp_reg_params: "Regional Parameters *",
        modal_add_dp_adr: "ADR Algorithm",
        modal_add_dp_otaa_check: "Supports OTAA (Over-The-Air Activation)",
        modal_add_dp_class_b_check: "Supports Class B",
        modal_add_dp_class_c_check: "Supports Class C",
        modal_add_dp_name_placeholder: "e.g. EU868 OTAA Profile",

        modal_add_net_title: "Add New Network",
        modal_add_net_tenant: "Tenant (Organization) *",
        modal_add_net_desc: "Description (optional)",
        modal_add_net_desc_placeholder: "Network description",
        modal_add_net_name_placeholder: "e.g. Sensor Network",

        modal_add_dev_title: "Add New Device",
        modal_add_dev_eui_label: "DevEUI * (16 hex chars)",
        modal_add_dev_app: "Network *",
        modal_add_dev_select_app_first: "Select network first",
        select_org_first: "Select organization first",
        select_app_first: "Select network first",
        modal_add_dev_desc: "Description (optional)",
        modal_add_dev_desc_placeholder: "Device description",
        modal_add_dev_name_placeholder: "e.g. Sensor-001",

        dev_wiz_step_1: "1. Organization & Network",
        dev_wiz_step_2: "2. Device Details",
        dev_wiz_step_3: "3. Summary & Confirmation",
        dev_wiz_summary_title: "Created Device Summary",
        dev_wiz_summary_subtitle: "Please confirm the details below.",
        dev_wiz_summary_confirm: "Do you confirm creating this device?",

        wiz_step_1: "1. Organization",
        wiz_step_2: "2. Network",
        wiz_step_3: "3. Profile",
        wiz_step_4: "4. Device",
        wiz_step_5: "5. Summary",
        wiz_org_hint: "New tenant/organization name to be created.",
        wiz_app_prefix: "Network Prefix *",
        wiz_app_count: "Networks to Create *",
        wiz_app_count_hint: "e.g. User-X-ag-1, User-X-ag-2...",
        wiz_dp_prefix: "Device Profile Prefix *",
        wiz_dp_count: "Profiles to Create *",
        wiz_dp_count_hint: "e.g. User-X-profile-1, User-X-profile-2...",
        wiz_dev_prefix: "Device Prefix *",
        wiz_dev_count: "Devices per Network *",
        wiz_dev_count_hint: "Number of devices to create in each network.",
        wiz_summary_title: "Configuration Summary",
        wiz_summary_subtitle: "Please customize LoRaWAN uplink intervals and profiles before confirming.",
        wiz_summary_org_lbl: "Org:",
        wiz_summary_net_lbl: "Net:",
        wiz_summary_dp_lbl: "Profile:",
        wiz_summary_unit: "qty",
        wiz_table_dev_template: "Device Template",
        wiz_summary_confirm_text: "Do you confirm this setup?",
        wiz_success_title: "Setup Completed Successfully",
        wiz_success_subtitle: "ChirpStack creation confirmation report",
        wiz_success_org_lbl: "Organization:",
        wiz_success_total_dev_lbl: "Total Devices:",
        wiz_success_dev_created_unit: "devices created.",
        wiz_success_net_created_lbl: "Created Networks:",
        net_wiz_step_1: "1. Organization",
        net_wiz_step_2: "2. Network Details",
        net_wiz_step_3: "3. Summary & Confirm",
        wiz_success_dp_created_lbl: "Created Device Profiles:",
        wiz_btn_confirm: "Confirm & Create",
        wiz_btn_close: "Close",
        wiz_btn_creating: "Creating...",
        btn_close: "Close",
        prev_page: "Prev",
        next_page: "Next"
    }
};

export function t(key) {
    const lang = state.language || "tr";
    const dict = translations[lang] || translations["tr"];
    return dict[key] || key;
}

export function translateDOM() {
    const elements = document.querySelectorAll("[data-i18n]");
    elements.forEach(el => {
        const key = el.getAttribute("data-i18n");
        const translation = t(key);
        if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") {
            el.placeholder = translation;
        } else if (el.tagName === "OPTION") {
            el.textContent = translation;
        } else {
            if (el.getAttribute("data-i18n-html") === "true") {
                el.innerHTML = translation;
            } else {
                el.textContent = translation;
            }
        }
    });

    const placeholders = document.querySelectorAll("[data-i18n-placeholder]");
    placeholders.forEach(el => {
        const key = el.getAttribute("data-i18n-placeholder");
        el.placeholder = t(key);
    });

    const titles = document.querySelectorAll("[data-i18n-title]");
    titles.forEach(el => {
        const key = el.getAttribute("data-i18n-title");
        el.title = t(key);
    });

    document.title = t("app_title");
}
